### ISSUE TITLE
Runner will exit shortly for update, should back online within 10 seconds. loop

### ISSUE THREAD

**Issue by RemyyB** [myoung34/docker-github-actions-runner#12] opened 2020-04-03 15:48 UTC
Hi there, I just setup a new runner, only the runner has an update, when I tail the logs I see: 

`Runner update in progress, do not shutdown runner.
Downloading 2.168.0 runner
Waiting for current job finish running.
Generate and execute update script.
Runner will exit shortly for update, should back online within 10 seconds.`

**Comment by myoung34** [comment] 2020-04-03 16:12
It doesnt look like you're running 2.168.0: 

you can either use myoung34/github-runner:2.168.0 or myoung34/github-runner:latest

At this time it doesnt look like [you can opt out of auto updates](https://github.com/actions/runner/issues/246) aside from that 

It looks like github somehow lost all my actions history for tags/releases, im going to kick off a new rebuild just in case and make sure it works as expected (since i cant double check how it built the last one)

**Comment by RemyyB** [comment] 2020-04-03 16:53
Hi there, thanks for your quick response. I tried to run with docker image myoung34/github-runner:2.168.0 and tried to pull :latest again, but it still tries to update to the latest version :/

Btw I have another runner running and that one's working for 4 days now, still working, but this one was stopped and tried to redownload? Both running for some time now and it always worked fine

**Comment by myoung34** [comment] 2020-04-03 17:38
@RemyyB for some reason GH actions isnt building the right version, so this is a bug. Ill figure it out, thanks for notifying  me!

**Comment by RemyyB** [comment] 2020-04-03 20:31
No probs, I hope it will be fixed :P, have a nice weekend!

**Comment by myoung34** [comment] 2020-04-03 20:32
They should be up for testing and good to go if you want to try

**Comment by RemyyB** [comment] 2020-04-03 20:42
Thanks, will try to pull latest tomorrow, you'll hear back :)

**Comment by myoung34** [comment] 2020-04-04 00:53
I confirmed earlier that this is using the right package now:

```
#13 [linux/arm64 7/9] RUN chmod +x /actions-runner/install_actions.sh   && /...
#13 0.180 + GH_RUNNER_VERSION=2.168.0
#13 0.181 + TARGETPLATFORM=linux/arm64
#13 0.183 + export TARGET_ARCH=x64
#13 0.184 + TARGET_ARCH=x64
#13 0.187 + [[ linux/arm64 == \l\i\n\u\x\/\a\r\m\/\v\7 ]]
#13 0.187 + [[ linux/arm64 == \l\i\n\u\x\/\a\r\m\6\4 ]]
#13 0.188 + export TARGET_ARCH=arm64
#13 0.188 + TARGET_ARCH=arm64
#13 0.190 + curl -L https://github.com/actions/runner/releases/download/v2.168.0/actions-runner-linux-arm64-2.168.0.tar.gz
```

im going to go ahead and close it to sign off, if this is still an issue just reopen it. 🍻

**Comment by RemyyB** [comment] 2020-04-09 20:42
Hi there,

The fix before worked, however when running for some time on push it wants to auto update itself on new versions, is there anyway this could be automated or fixed permanently so it can auto update itself without having to redo my whole runner ;(

Thanks in advance, you're a hero :)

Remy

**Comment by myoung34** [comment] 2020-04-10 00:52
There's not: https://github.com/actions/runner/issues/246

**Comment by bryanmacfarlane** [comment] 2020-04-17 14:52
> is there anyway this could be automated or fixed permanently so it can auto update itself without having to redo my whole runner 

Yes there is :)

The docker calls `./run.sh` here: https://github.com/myoung34/docker-github-actions-runner/blob/master/entrypoint.sh#L29

It should call `./runsvc.sh` which will handle the updates and you won't get into an endless loop.  That's the entrypoint that we call when we run the runner as a service.

run.sh is for interactive running

**Comment by myoung34** [comment] 2020-04-17 17:44
Do you have any examples of calling `runsvc.h` directly? 
That file looks like its run in the background from a node call directly

The run.shs calls Runner.Listener and some other things which look a bit different

**Comment by bryanmacfarlane** [comment] 2020-04-18 20:30
Run.sh call the listener (that's actually the runner that listens to the queue)

Runsvc.sh calls a node process script (works on all OSes) which handles update return codes and calls the listener.  It puts a process in the middle to handle updates etc.

If you configure the runner as a service (./svc.sh which creates systemd (linux), launchd (osx) or windows svc) notice the config files that generates points to runsvc.sh as the entry point.

I'll create a sample container soon.  But if you want to try it out, replace run.sh with runsvc.sh.  hth

**Comment by RemyyB** [comment] 2020-05-04 09:06
Any update on this? ;)

**Comment by myoung34** [comment] 2020-05-04 13:47
Not from my side, we're having power fluctuations and long periods without power, but it's on my eventual to-do

**Comment by myoung34** [comment] 2020-05-11 19:47
The change has been made in https://github.com/myoung34/docker-github-actions-runner/commit/5080efc02ce45e4205e9e4edc2605eca88d608ff

itll be pushed as latest as well as 2.262.0 which just dropped

**Closed as completed by myoung34** 2020-05-11 19:47 UTC
