### ISSUE TITLE
Checkout fails in workflow

### ISSUE THREAD

**Issue by skumra** [myoung34/docker-github-actions-runner#279] opened 2023-02-01 23:55 UTC
Firstly, thank you for sharing this amazing work.

I have set up runners using this implementation and can see the workflow run in these runners. But the workflow fails during the repository checkout step. The workflow runs fine in Github or regular self-hosted runners.

Here is my workflow:
```
jobs:
  clang-format:
    runs-on: self-hosted
    strategy:
      fail-fast: true
    container:
      image: my_image:latest
      options: --user root
      credentials:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
```

Here is the error log:
```
Run actions/checkout@v3
/usr/bin/docker exec  <sha> sh -c "cat /etc/*release | grep ^ID"
OCI runtime exec failed: exec failed: unable to start container process: exec: "/__e/node12/bin/node": stat /__e/node12/bin/node: no such file or directory: unknown
```

Thank you in advance for your help.

**Comment by tanarurkerem** [comment] 2023-02-02 04:24
I found this issue: https://github.com/actions/checkout/issues/334
If you would like to read only one comment: https://github.com/actions/checkout/issues/334#issuecomment-1241306390
Tip: Try checkout v1

**Comment by myoung34** [comment] 2023-02-02 08:42
This is a dupe of https://github.com/myoung34/docker-github-actions-runner/issues/261

The issue isnt with cat /etc/release or checkout, its that its attempting to use DinD which is documented as unsupported upstream

if you feel like I mis-diagnosed please reopen with more information

**Comment by myoung34** [comment] 2023-02-02 08:42
This is a dupe of https://github.com/myoung34/docker-github-actions-runner/issues/261

The issue isnt with cat /etc/release or checkout, its that its attempting to use DinD which is documented as unsupported upstream

if you feel like I mis-diagnosed please reopen with more information

**Closed as completed by myoung34** 2023-02-02 08:42 UTC
