### ISSUE TITLE
myoung34/github-runner:2.293.0 fails to start

### ISSUE THREAD

**Issue by juhhov** [myoung34/docker-github-actions-runner#216] opened 2022-06-14 07:55 UTC
2.293.0 image fails to start with following error:

```
Runner reusage is disabled
Obtaining the token of the runner
curl: (6) getaddrinfo() thread failed to start
Disable auto update option is enabled
Configuring
Failed to create CoreCLR, HRESULT: 0x80070008
Failed to create CoreCLR, HRESULT: 0x80070008
```

Runner starts normally when using `2.293.0-ubuntu-focal` tag. Most likely relates to default tag moving to ubuntu 22.04?

**Comment by myoung34** [comment] 2022-06-14 18:08
I think your issue is deeper: 

```
Obtaining the token of the runner
curl: (6) getaddrinfo() thread failed to start
```

That seems host related. I just ran it locally:

```
Runner reusage is disabled
Disable auto update option is enabled
Configuring

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication


√ Connected to GitHub

# Runner Registration




√ Runner successfully added
√ Runner connection is good

# Runner settings


√ Settings Saved.


√ Connected to GitHub

Current runner version: '2.293.0'
2022-06-14 18:07:24Z: Listening for Jobs
```

Your error stems first at [this call](https://github.com/myoung34/docker-github-actions-runner/blob/master/entrypoint.sh#L62-L66) then [here](https://github.com/myoung34/docker-github-actions-runner/blob/master/token.sh#L37-L42) for the curl error.

Id recommend digging into whatever is causing cURL to fail with `curl: (6) getaddrinfo() thread failed to start`

Unless others follow up that this is widespread it all looks fine and worked on my side, so Ill close it for now. Feel free to reopen if that seems incorrect (with some indicators to why) and we can dig deeper.

**Closed as completed** 2022-06-14 18:11 UTC

**Comment by juhhov** [comment] 2022-06-15 07:03
Thanks for your fast input. Seems like this is indeed related to host. We have Ubuntu 20.04 based hosts. I found this https://askubuntu.com/a/1410408.
We downgraded the github-runner image to 20.04 for now.

**Comment by bungabear** [comment] 2022-06-15 12:15
When I updated to github-runner::2.293.0, It occurs. 
My host OS is Centos 8.4.2105 and Docker version 20.10.7.

Downgraded version github-runner:2.289.2 works well.

**Comment by tk098398** [comment] 2022-06-16 02:40
When I updated to github-runner::2.293.0, It occurs.
My host OS is Centos 7.7.1908 (Core) and Docker version 20.10.1.

```
Failed to create CoreCLR, HRESULT: 0x80070008
Runner reusage is disabled
Obtaining the token of the runner
curl: (6) getaddrinfo() thread failed to start
Configuring
ldd: error: you do not have read permission for `./bin/libcoreclr.so'
ldd: error: you do not have read permission for `./bin/libSystem.Security.Cryptography.Native.OpenSsl.so'
ldd: error: you do not have read permission for `./bin/libSystem.IO.Compression.Native.so'
Can not find 'ldconfig' in PATH and '/sbin/ldconfig' doesn't exists either. Please install 'ldconfig' and try again.
Failed to create CoreCLR, HRESULT: 0x80070008

```
Downgraded version github-runner:2.292.0 works well.

**Comment by myoung34** [comment] 2022-06-16 02:42
Again this is not an issue with this runner but the host. @juhhov listed there potential issue

**Comment by Ru13en** [comment] 2022-06-18 01:58
@tk098398 and @juhhov 
This issue is caused by Docker engine. Older versions of Docker engine are not compatible with jammy-based containers. 
You must install Docker engine to at least version 20.10.10.
Otherwise, if you don't want to upgrade the docker engine, you must add --security-opt seccomp=unconfined option to runner.
Docker engine before version 20.10.10 cant manage security-opt very well and jammy-based containers require better management or none at all...

**Comment by tk098398** [comment] 2022-06-19 22:57
@Ru13en 
I very much appreciated your response.
I'll try.
